### ISSUE TITLE
Change roadside page layout

### ISSUE THREAD

**Issue by Smittyvb** [Smittyvb/roadsides-www#12]
- [ ] Put the title on top of the image, and the other information at the bottom.
- [ ] Remove word "location" and similar words before other sections of the text (except keep the word credit)
- [ ] where no GPS info, insert 'Google Maps' link instead
- [ ] 2 line breaks after the city/province info
- [ ] 2 line breaks after location info
- [ ] 2 line breaks after description info

_edit: combined with @dr-mvb's list_

**Comment by dr-mvb** [comment]
- also: remove word "location" and similar words before other sections of the text (except keep the word credit)
- where no GPS info, insert 'Google Maps' link instead
- line break after the city/province info
- line break after location info
- line break after description info

**Comment by Smittyvb** [comment]
What does this mean: "where no GPS info, insert 'Google Maps' link instead"

**Comment by dr-mvb** [comment]
On roadside pages where we have GPS coords, there will be a "Google Maps" link which goes to a Google Map at those coordinates. Currently, where we don't have coords, there is no "Google Maps" link.

However, I am suggesting that for roadsides where we don't have GPS coords, there should still be a link that says "Google Maps" but instead of going to specific coords (which we don't have), it should go to our main Google Map with all the roadsides on it (that is, the same link on left side of the page that says "Google Maps").

**Comment by Smittyvb** [comment]
Got it!
